export function getImoveis() {
  return [
    {
      id: 1,
      tipo: "Apartamento",
      endereco: "Rua A, 123",
      cidade: "São Paulo",
      estado: "SP",
      preco: 450000,
      imagem: "imovel1.png",
      latitude: -23.55,
      longitude: -46.63,
      quartos: 3,
      banheiros: 2,
    },
    {
      id: 2,
      tipo: "Casa",
      endereco: "Rua B, 456",
      cidade: "São Paulo",
      estado: "SP",
      preco: 750000,
      imagem: "/imovel2.png",
      latitude: -23.56,
      longitude: -46.62,
      quartos: 4,
      banheiros: 3,
    },
    {
      id: 3,
      tipo: "Cobertura",
      endereco: "Rua C, 789",
      cidade: "São Paulo",
      estado: "SP",
      preco: 1200000,
      imagem: "/imovel3.png",
      latitude: -23.54,
      longitude: -46.64,
      quartos: 5,
      banheiros: 4,
    },
    {
      id: 4,
      tipo: "Apartamento",
      endereco: "Rua D, 101",
      cidade: "São Paulo",
      estado: "SP",
      preco: 500000,
      imagem: "/imovel1.png",
      latitude: -23.57,
      longitude: -46.65,
      quartos: 2,
      banheiros: 1,
    },
    {
      id: 5,
      tipo: "Casa",
      endereco: "Rua E, 202",
      cidade: "São Paulo",
      estado: "SP",
      preco: 800000,
      imagem: "/imovel1.png",
      latitude: -23.58,
      longitude: -46.66,
      quartos: 3,
      banheiros: 2,
    },
    {
      id: 6,
      tipo: "Apartamento",
      endereco: "Rua F, 303",
      cidade: "São Paulo",
      estado: "SP",
      preco: 600000,
      imagem: "/imovel1.png",
      latitude: -23.59,
      longitude: -46.67,
      quartos: 3,
      banheiros: 2,
    },
    {
      id: 7,
      tipo: "Cobertura",
      endereco: "Rua G, 404",
      cidade: "São Paulo",
      estado: "SP",
      preco: 1300000,
      imagem: "/imovel1.png",
      latitude: -23.6,
      longitude: -46.68,
      quartos: 4,
      banheiros: 3,
    },
    {
      id: 8,
      tipo: "Casa",
      endereco: "Rua H, 505",
      cidade: "São Paulo",
      estado: "SP",
      preco: 900000,
      imagem: "/imovel1.png",
      latitude: -23.61,
      longitude: -46.69,
      quartos: 5,
      banheiros: 4,
    },
    {
      id: 9,
      tipo: "Apartamento",
      endereco: "Rua I, 606",
      cidade: "São Paulo",
      estado: "SP",
      preco: 550000,
      imagem: "/imovel1.png",
      latitude: -23.62,
      longitude: -46.7,
      quartos: 2,
      banheiros: 1,
    },
  ];
}
