export async function getRelatorioData(tipo) {
  return {
    imoveis: {
      totalApartamentos: 31,
      totalCasas: 22,
      totalTerrenos: 20,
      totalImoveis: 73,
      imoveisPorAcesso: [
        {
          id: 2,
          tipo: "Apartamento",
          endereco: "Av. Brasil, 456",
          preco: 1200000.0,
          acessos: 9,
        },
        {
          id: 6,
          tipo: "Terreno",
          endereco: "Rua Sul, 852",
          preco: 180000.0,
          acessos: 8,
        },
        {
          id: 4,
          tipo: "Casa",
          endereco: "Rua Azul, 321",
          preco: 3500.0,
          acessos: 6,
        },
        {
          id: 3,
          tipo: "Terreno",
          endereco: "Rua Verde, 789",
          preco: 250000.0,
          acessos: 6,
        },
        {
          id: 10,
          tipo: "Casa",
          endereco: "Rua Centro, 369",
          preco: 500000.0,
          acessos: 5,
        },
        {
          id: 33,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 123",
          preco: 255000.0,
          acessos: 4,
        },
        {
          id: 41,
          tipo: "Casa",
          endereco: "Rua das Azaleias, 456",
          preco: 355000.0,
          acessos: 4,
        },
        {
          id: 49,
          tipo: "Terreno",
          endereco: "Rua M, 890",
          preco: 145000.0,
          acessos: 4,
        },
        {
          id: 1,
          tipo: "Casa",
          endereco: "Rua das Flores, 123",
          preco: 550000.0,
          acessos: 4,
        },
        {
          id: 57,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 890",
          preco: 315000.0,
          acessos: 4,
        },
        {
          id: 9,
          tipo: "Terreno",
          endereco: "Rua Oeste, 258",
          preco: 300000.0,
          acessos: 4,
        },
        {
          id: 65,
          tipo: "Casa",
          endereco: "Rua dos Crisântemos, 890",
          preco: 365000.0,
          acessos: 4,
        },
        {
          id: 17,
          tipo: "Casa",
          endereco: "Rua dos Ipês, 345",
          preco: 380000.0,
          acessos: 4,
        },
        {
          id: 73,
          tipo: "Terreno",
          endereco: "Rua U, 678",
          preco: 155000.0,
          acessos: 4,
        },
        {
          id: 25,
          tipo: "Terreno",
          endereco: "Rua E, 123",
          preco: 120000.0,
          acessos: 4,
        },
        {
          id: 32,
          tipo: "Casa",
          endereco: "Rua das Orquídeas, 890",
          preco: 395000.0,
          acessos: 4,
        },
        {
          id: 40,
          tipo: "Terreno",
          endereco: "Rua J, 678",
          preco: 125000.0,
          acessos: 4,
        },
        {
          id: 48,
          tipo: "Apartamento",
          endereco: "Rua Guiana, 567",
          preco: 225000.0,
          acessos: 4,
        },
        {
          id: 56,
          tipo: "Casa",
          endereco: "Rua das Dálias, 567",
          preco: 375000.0,
          acessos: 4,
        },
        {
          id: 8,
          tipo: "Apartamento",
          endereco: "Av. Leste, 147",
          preco: 600000.0,
          acessos: 4,
        },
        {
          id: 64,
          tipo: "Terreno",
          endereco: "Rua R, 345",
          preco: 95000.0,
          acessos: 4,
        },
        {
          id: 16,
          tipo: "Terreno",
          endereco: "Rua B, 890",
          preco: 95000.0,
          acessos: 4,
        },
        {
          id: 72,
          tipo: "Apartamento",
          endereco: "Rua Peru, 345",
          preco: 225000.0,
          acessos: 4,
        },
        {
          id: 24,
          tipo: "Apartamento",
          endereco: "Rua Chile, 890",
          preco: 225000.0,
          acessos: 4,
        },
        {
          id: 31,
          tipo: "Terreno",
          endereco: "Rua G, 345",
          preco: 165000.0,
          acessos: 4,
        },
        {
          id: 39,
          tipo: "Apartamento",
          endereco: "Rua Equador, 345",
          preco: 295000.0,
          acessos: 4,
        },
        {
          id: 47,
          tipo: "Casa",
          endereco: "Rua das Camélias, 234",
          preco: 325000.0,
          acessos: 4,
        },
        {
          id: 55,
          tipo: "Terreno",
          endereco: "Rua O, 012",
          preco: 165000.0,
          acessos: 4,
        },
        {
          id: 7,
          tipo: "Casa",
          endereco: "Rua Norte, 963",
          preco: 450000.0,
          acessos: 4,
        },
        {
          id: 63,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 012",
          preco: 325000.0,
          acessos: 4,
        },
        {
          id: 15,
          tipo: "Apartamento",
          endereco: "Rua Portugal, 567",
          preco: 190000.0,
          acessos: 4,
        },
        {
          id: 71,
          tipo: "Casa",
          endereco: "Rua dos Girassóis, 012",
          preco: 375000.0,
          acessos: 4,
        },
        {
          id: 23,
          tipo: "Casa",
          endereco: "Rua dos Jacarandás, 567",
          preco: 410000.0,
          acessos: 4,
        },
        {
          id: 30,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 012",
          preco: 245000.0,
          acessos: 4,
        },
        {
          id: 38,
          tipo: "Casa",
          endereco: "Rua das Margaridas, 012",
          preco: 405000.0,
          acessos: 4,
        },
        {
          id: 46,
          tipo: "Terreno",
          endereco: "Rua L, 789",
          preco: 135000.0,
          acessos: 4,
        },
        {
          id: 54,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 789",
          preco: 195000.0,
          acessos: 4,
        },
        {
          id: 62,
          tipo: "Casa",
          endereco: "Rua das Rosas, 789",
          preco: 395000.0,
          acessos: 4,
        },
        {
          id: 14,
          tipo: "Casa",
          endereco: "Rua Amazonas, 234",
          preco: 420000.0,
          acessos: 4,
        },
        {
          id: 70,
          tipo: "Terreno",
          endereco: "Rua T, 567",
          preco: 125000.0,
          acessos: 4,
        },
        {
          id: 22,
          tipo: "Terreno",
          endereco: "Rua D, 012",
          preco: 180000.0,
          acessos: 4,
        },
        {
          id: 29,
          tipo: "Casa",
          endereco: "Rua dos Lírios, 789",
          preco: 370000.0,
          acessos: 4,
        },
        {
          id: 37,
          tipo: "Terreno",
          endereco: "Rua I, 567",
          preco: 175000.0,
          acessos: 4,
        },
        {
          id: 45,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          preco: 305000.0,
          acessos: 4,
        },
        {
          id: 53,
          tipo: "Casa",
          endereco: "Rua das Begônias, 456",
          preco: 345000.0,
          acessos: 4,
        },
        {
          id: 5,
          tipo: "Apartamento",
          endereco: "Av. Central, 654",
          preco: 800000.0,
          acessos: 4,
        },
        {
          id: 61,
          tipo: "Terreno",
          endereco: "Rua Q, 234",
          preco: 185000.0,
          acessos: 4,
        },
        {
          id: 13,
          tipo: "Terreno",
          endereco: "Rua das Flores, 789",
          preco: 150000.0,
          acessos: 4,
        },
        {
          id: 69,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 234",
          preco: 335000.0,
          acessos: 4,
        },
        {
          id: 21,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 789",
          preco: 265000.0,
          acessos: 4,
        },
        {
          id: 28,
          tipo: "Terreno",
          endereco: "Rua F, 234",
          preco: 195000.0,
          acessos: 4,
        },
        {
          id: 36,
          tipo: "Apartamento",
          endereco: "Rua Peru, 234",
          preco: 235000.0,
          acessos: 4,
        },
        {
          id: 44,
          tipo: "Casa",
          endereco: "Rua das Gardênias, 123",
          preco: 385000.0,
          acessos: 4,
        },
        {
          id: 52,
          tipo: "Terreno",
          endereco: "Rua N, 901",
          preco: 115000.0,
          acessos: 4,
        },
        {
          id: 60,
          tipo: "Apartamento",
          endereco: "Rua Chile, 901",
          preco: 205000.0,
          acessos: 4,
        },
        {
          id: 12,
          tipo: "Apartamento",
          endereco: "Av. Prefeito Jonas Banks, 456",
          preco: 280000.0,
          acessos: 4,
        },
        {
          id: 68,
          tipo: "Casa",
          endereco: "Rua dos Antúrios, 901",
          preco: 405000.0,
          acessos: 4,
        },
        {
          id: 20,
          tipo: "Casa",
          endereco: "Rua das Palmeiras, 456",
          preco: 290000.0,
          acessos: 4,
        },
        {
          id: 27,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 901",
          preco: 275000.0,
          acessos: 4,
        },
        {
          id: 35,
          tipo: "Casa",
          endereco: "Rua das Violetas, 901",
          preco: 315000.0,
          acessos: 4,
        },
        {
          id: 43,
          tipo: "Terreno",
          endereco: "Rua K, 890",
          preco: 155000.0,
          acessos: 4,
        },
        {
          id: 51,
          tipo: "Apartamento",
          endereco: "Rua Suriname, 678",
          preco: 285000.0,
          acessos: 4,
        },
        {
          id: 59,
          tipo: "Casa",
          endereco: "Rua das Tulipas, 678",
          preco: 335000.0,
          acessos: 4,
        },
        {
          id: 11,
          tipo: "Casa",
          endereco: "Rua São João, 123",
          preco: 350000.0,
          acessos: 4,
        },
        {
          id: 67,
          tipo: "Terreno",
          endereco: "Rua S, 456",
          preco: 175000.0,
          acessos: 4,
        },
        {
          id: 19,
          tipo: "Terreno",
          endereco: "Rua C, 901",
          preco: 220000.0,
          acessos: 4,
        },
        {
          id: 34,
          tipo: "Terreno",
          endereco: "Rua H, 456",
          preco: 140000.0,
          acessos: 4,
        },
        {
          id: 42,
          tipo: "Apartamento",
          endereco: "Rua Colômbia, 789",
          preco: 215000.0,
          acessos: 4,
        },
        {
          id: 50,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 345",
          preco: 365000.0,
          acessos: 4,
        },
        {
          id: 58,
          tipo: "Terreno",
          endereco: "Rua P, 123",
          preco: 105000.0,
          acessos: 4,
        },
        {
          id: 66,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 123",
          preco: 215000.0,
          acessos: 4,
        },
        {
          id: 18,
          tipo: "Apartamento",
          endereco: "Av. Brasil, 678",
          preco: 310000.0,
          acessos: 4,
        },
        {
          id: 26,
          tipo: "Casa",
          endereco: "Rua das Acácias, 678",
          preco: 330000.0,
          acessos: 4,
        },
        {
          id: 81,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 901",
          preco: 355000.0,
          acessos: 3,
        },
        {
          id: 89,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 901",
          preco: 405000.0,
          acessos: 3,
        },
        {
          id: 97,
          tipo: "Terreno",
          endereco: "Rua 3, 567",
          preco: 175000.0,
          acessos: 3,
        },
        {
          id: 105,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 789",
          preco: 395000.0,
          acessos: 3,
        },
        {
          id: 80,
          tipo: "Casa",
          endereco: "Rua das Buganvílias, 678",
          preco: 425000.0,
          acessos: 3,
        },
        {
          id: 88,
          tipo: "Terreno",
          endereco: "Rua Z, 234",
          preco: 105000.0,
          acessos: 3,
        },
        {
          id: 96,
          tipo: "Apartamento",
          endereco: "Rua Chile, 456",
          preco: 265000.0,
          acessos: 3,
        },
        {
          id: 104,
          tipo: "Casa",
          endereco: "Rua das Dálias, 456",
          preco: 465000.0,
          acessos: 3,
        },
        {
          id: 79,
          tipo: "Terreno",
          endereco: "Rua W, 901",
          preco: 165000.0,
          acessos: 3,
        },
        {
          id: 87,
          tipo: "Apartamento",
          endereco: "Rua Suriname, 123",
          preco: 365000.0,
          acessos: 3,
        },
        {
          id: 95,
          tipo: "Casa",
          endereco: "Rua das Gardênias, 123",
          preco: 415000.0,
          acessos: 3,
        },
        {
          id: 103,
          tipo: "Terreno",
          endereco: "Rua 5, 789",
          preco: 185000.0,
          acessos: 3,
        },
        {
          id: 86,
          tipo: "Casa",
          endereco: "Rua dos Jasmins, 890",
          preco: 435000.0,
          acessos: 3,
        },
        {
          id: 94,
          tipo: "Terreno",
          endereco: "Rua 2, 456",
          preco: 125000.0,
          acessos: 3,
        },
        {
          id: 102,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 678",
          preco: 275000.0,
          acessos: 3,
        },
        {
          id: 78,
          tipo: "Apartamento",
          endereco: "Rua Colômbia, 890",
          preco: 235000.0,
          acessos: 3,
        },
        {
          id: 85,
          tipo: "Terreno",
          endereco: "Rua Y, 123",
          preco: 185000.0,
          acessos: 3,
        },
        {
          id: 93,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 345",
          preco: 375000.0,
          acessos: 3,
        },
        {
          id: 101,
          tipo: "Casa",
          endereco: "Rua das Begônias, 345",
          preco: 425000.0,
          acessos: 3,
        },
        {
          id: 109,
          tipo: "Terreno",
          endereco: "Rua 7, 901",
          preco: 195000.0,
          acessos: 3,
        },
        {
          id: 77,
          tipo: "Casa",
          endereco: "Rua das Alamandas, 567",
          preco: 385000.0,
          acessos: 3,
        },
        {
          id: 84,
          tipo: "Apartamento",
          endereco: "Rua Guiana, 012",
          preco: 245000.0,
          acessos: 3,
        },
        {
          id: 92,
          tipo: "Casa",
          endereco: "Rua das Azaleias, 012",
          preco: 445000.0,
          acessos: 3,
        },
        {
          id: 100,
          tipo: "Terreno",
          endereco: "Rua 4, 678",
          preco: 135000.0,
          acessos: 3,
        },
        {
          id: 108,
          tipo: "Apartamento",
          endereco: "Rua Peru, 890",
          preco: 285000.0,
          acessos: 3,
        },
        {
          id: 76,
          tipo: "Terreno",
          endereco: "Rua V, 890",
          preco: 135000.0,
          acessos: 3,
        },
        {
          id: 83,
          tipo: "Casa",
          endereco: "Rua das Primaveras, 789",
          preco: 395000.0,
          acessos: 3,
        },
        {
          id: 91,
          tipo: "Terreno",
          endereco: "Rua 1, 345",
          preco: 195000.0,
          acessos: 3,
        },
        {
          id: 99,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 567",
          preco: 385000.0,
          acessos: 3,
        },
        {
          id: 107,
          tipo: "Casa",
          endereco: "Rua das Tulipas, 567",
          preco: 435000.0,
          acessos: 3,
        },
        {
          id: 75,
          tipo: "Apartamento",
          endereco: "Rua Equador, 789",
          preco: 345000.0,
          acessos: 3,
        },
        {
          id: 82,
          tipo: "Terreno",
          endereco: "Rua X, 012",
          preco: 115000.0,
          acessos: 3,
        },
        {
          id: 90,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 234",
          preco: 255000.0,
          acessos: 3,
        },
        {
          id: 98,
          tipo: "Casa",
          endereco: "Rua das Camélias, 234",
          preco: 455000.0,
          acessos: 3,
        },
        {
          id: 106,
          tipo: "Terreno",
          endereco: "Rua 6, 890",
          preco: 145000.0,
          acessos: 3,
        },
        {
          id: 74,
          tipo: "Casa",
          endereco: "Rua das Magnólias, 456",
          preco: 415000.0,
          acessos: 3,
        },
        {
          id: 110,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          preco: 358800.0,
          acessos: 0,
        },
      ],
      imoveisPorPreco: [
        {
          id: 1,
          tipo: "Casa",
          endereco: "Rua das Flores, 123",
          preco: 550000.0,
        },
        {
          id: 2,
          tipo: "Apartamento",
          endereco: "Av. Brasil, 456",
          preco: 1200000.0,
        },
        {
          id: 3,
          tipo: "Terreno",
          endereco: "Rua Verde, 789",
          preco: 250000.0,
        },
        {
          id: 4,
          tipo: "Casa",
          endereco: "Rua Azul, 321",
          preco: 3500.0,
        },
        {
          id: 5,
          tipo: "Apartamento",
          endereco: "Av. Central, 654",
          preco: 800000.0,
        },
        {
          id: 6,
          tipo: "Terreno",
          endereco: "Rua Sul, 852",
          preco: 180000.0,
        },
        {
          id: 7,
          tipo: "Casa",
          endereco: "Rua Norte, 963",
          preco: 450000.0,
        },
        {
          id: 8,
          tipo: "Apartamento",
          endereco: "Av. Leste, 147",
          preco: 600000.0,
        },
        {
          id: 9,
          tipo: "Terreno",
          endereco: "Rua Oeste, 258",
          preco: 300000.0,
        },
        {
          id: 10,
          tipo: "Casa",
          endereco: "Rua Centro, 369",
          preco: 500000.0,
        },
        {
          id: 11,
          tipo: "Casa",
          endereco: "Rua São João, 123",
          preco: 350000.0,
        },
        {
          id: 12,
          tipo: "Apartamento",
          endereco: "Av. Prefeito Jonas Banks, 456",
          preco: 280000.0,
        },
        {
          id: 13,
          tipo: "Terreno",
          endereco: "Rua das Flores, 789",
          preco: 150000.0,
        },
        {
          id: 14,
          tipo: "Casa",
          endereco: "Rua Amazonas, 234",
          preco: 420000.0,
        },
        {
          id: 15,
          tipo: "Apartamento",
          endereco: "Rua Portugal, 567",
          preco: 190000.0,
        },
        {
          id: 16,
          tipo: "Terreno",
          endereco: "Rua B, 890",
          preco: 95000.0,
        },
        {
          id: 17,
          tipo: "Casa",
          endereco: "Rua dos Ipês, 345",
          preco: 380000.0,
        },
        {
          id: 18,
          tipo: "Apartamento",
          endereco: "Av. Brasil, 678",
          preco: 310000.0,
        },
        {
          id: 19,
          tipo: "Terreno",
          endereco: "Rua C, 901",
          preco: 220000.0,
        },
        {
          id: 20,
          tipo: "Casa",
          endereco: "Rua das Palmeiras, 456",
          preco: 290000.0,
        },
        {
          id: 21,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 789",
          preco: 265000.0,
        },
        {
          id: 22,
          tipo: "Terreno",
          endereco: "Rua D, 012",
          preco: 180000.0,
        },
        {
          id: 23,
          tipo: "Casa",
          endereco: "Rua dos Jacarandás, 567",
          preco: 410000.0,
        },
        {
          id: 24,
          tipo: "Apartamento",
          endereco: "Rua Chile, 890",
          preco: 225000.0,
        },
        {
          id: 25,
          tipo: "Terreno",
          endereco: "Rua E, 123",
          preco: 120000.0,
        },
        {
          id: 26,
          tipo: "Casa",
          endereco: "Rua das Acácias, 678",
          preco: 330000.0,
        },
        {
          id: 27,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 901",
          preco: 275000.0,
        },
        {
          id: 28,
          tipo: "Terreno",
          endereco: "Rua F, 234",
          preco: 195000.0,
        },
        {
          id: 29,
          tipo: "Casa",
          endereco: "Rua dos Lírios, 789",
          preco: 370000.0,
        },
        {
          id: 30,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 012",
          preco: 245000.0,
        },
        {
          id: 31,
          tipo: "Terreno",
          endereco: "Rua G, 345",
          preco: 165000.0,
        },
        {
          id: 32,
          tipo: "Casa",
          endereco: "Rua das Orquídeas, 890",
          preco: 395000.0,
        },
        {
          id: 33,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 123",
          preco: 255000.0,
        },
        {
          id: 34,
          tipo: "Terreno",
          endereco: "Rua H, 456",
          preco: 140000.0,
        },
        {
          id: 35,
          tipo: "Casa",
          endereco: "Rua das Violetas, 901",
          preco: 315000.0,
        },
        {
          id: 36,
          tipo: "Apartamento",
          endereco: "Rua Peru, 234",
          preco: 235000.0,
        },
        {
          id: 37,
          tipo: "Terreno",
          endereco: "Rua I, 567",
          preco: 175000.0,
        },
        {
          id: 38,
          tipo: "Casa",
          endereco: "Rua das Margaridas, 012",
          preco: 405000.0,
        },
        {
          id: 39,
          tipo: "Apartamento",
          endereco: "Rua Equador, 345",
          preco: 295000.0,
        },
        {
          id: 40,
          tipo: "Terreno",
          endereco: "Rua J, 678",
          preco: 125000.0,
        },
        {
          id: 41,
          tipo: "Casa",
          endereco: "Rua das Azaleias, 456",
          preco: 355000.0,
        },
        {
          id: 42,
          tipo: "Apartamento",
          endereco: "Rua Colômbia, 789",
          preco: 215000.0,
        },
        {
          id: 43,
          tipo: "Terreno",
          endereco: "Rua K, 890",
          preco: 155000.0,
        },
        {
          id: 44,
          tipo: "Casa",
          endereco: "Rua das Gardênias, 123",
          preco: 385000.0,
        },
        {
          id: 45,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          preco: 305000.0,
        },
        {
          id: 46,
          tipo: "Terreno",
          endereco: "Rua L, 789",
          preco: 135000.0,
        },
        {
          id: 47,
          tipo: "Casa",
          endereco: "Rua das Camélias, 234",
          preco: 325000.0,
        },
        {
          id: 48,
          tipo: "Apartamento",
          endereco: "Rua Guiana, 567",
          preco: 225000.0,
        },
        {
          id: 49,
          tipo: "Terreno",
          endereco: "Rua M, 890",
          preco: 145000.0,
        },
        {
          id: 50,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 345",
          preco: 365000.0,
        },
        {
          id: 51,
          tipo: "Apartamento",
          endereco: "Rua Suriname, 678",
          preco: 285000.0,
        },
        {
          id: 52,
          tipo: "Terreno",
          endereco: "Rua N, 901",
          preco: 115000.0,
        },
        {
          id: 53,
          tipo: "Casa",
          endereco: "Rua das Begônias, 456",
          preco: 345000.0,
        },
        {
          id: 54,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 789",
          preco: 195000.0,
        },
        {
          id: 55,
          tipo: "Terreno",
          endereco: "Rua O, 012",
          preco: 165000.0,
        },
        {
          id: 56,
          tipo: "Casa",
          endereco: "Rua das Dálias, 567",
          preco: 375000.0,
        },
        {
          id: 57,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 890",
          preco: 315000.0,
        },
        {
          id: 58,
          tipo: "Terreno",
          endereco: "Rua P, 123",
          preco: 105000.0,
        },
        {
          id: 59,
          tipo: "Casa",
          endereco: "Rua das Tulipas, 678",
          preco: 335000.0,
        },
        {
          id: 60,
          tipo: "Apartamento",
          endereco: "Rua Chile, 901",
          preco: 205000.0,
        },
        {
          id: 61,
          tipo: "Terreno",
          endereco: "Rua Q, 234",
          preco: 185000.0,
        },
        {
          id: 62,
          tipo: "Casa",
          endereco: "Rua das Rosas, 789",
          preco: 395000.0,
        },
        {
          id: 63,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 012",
          preco: 325000.0,
        },
        {
          id: 64,
          tipo: "Terreno",
          endereco: "Rua R, 345",
          preco: 95000.0,
        },
        {
          id: 65,
          tipo: "Casa",
          endereco: "Rua dos Crisântemos, 890",
          preco: 365000.0,
        },
        {
          id: 66,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 123",
          preco: 215000.0,
        },
        {
          id: 67,
          tipo: "Terreno",
          endereco: "Rua S, 456",
          preco: 175000.0,
        },
        {
          id: 68,
          tipo: "Casa",
          endereco: "Rua dos Antúrios, 901",
          preco: 405000.0,
        },
        {
          id: 69,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 234",
          preco: 335000.0,
        },
        {
          id: 70,
          tipo: "Terreno",
          endereco: "Rua T, 567",
          preco: 125000.0,
        },
        {
          id: 71,
          tipo: "Casa",
          endereco: "Rua dos Girassóis, 012",
          preco: 375000.0,
        },
        {
          id: 72,
          tipo: "Apartamento",
          endereco: "Rua Peru, 345",
          preco: 225000.0,
        },
        {
          id: 73,
          tipo: "Terreno",
          endereco: "Rua U, 678",
          preco: 155000.0,
        },
        {
          id: 74,
          tipo: "Casa",
          endereco: "Rua das Magnólias, 456",
          preco: 415000.0,
        },
        {
          id: 75,
          tipo: "Apartamento",
          endereco: "Rua Equador, 789",
          preco: 345000.0,
        },
        {
          id: 76,
          tipo: "Terreno",
          endereco: "Rua V, 890",
          preco: 135000.0,
        },
        {
          id: 77,
          tipo: "Casa",
          endereco: "Rua das Alamandas, 567",
          preco: 385000.0,
        },
        {
          id: 78,
          tipo: "Apartamento",
          endereco: "Rua Colômbia, 890",
          preco: 235000.0,
        },
        {
          id: 79,
          tipo: "Terreno",
          endereco: "Rua W, 901",
          preco: 165000.0,
        },
        {
          id: 80,
          tipo: "Casa",
          endereco: "Rua das Buganvílias, 678",
          preco: 425000.0,
        },
        {
          id: 81,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 901",
          preco: 355000.0,
        },
        {
          id: 82,
          tipo: "Terreno",
          endereco: "Rua X, 012",
          preco: 115000.0,
        },
        {
          id: 83,
          tipo: "Casa",
          endereco: "Rua das Primaveras, 789",
          preco: 395000.0,
        },
        {
          id: 84,
          tipo: "Apartamento",
          endereco: "Rua Guiana, 012",
          preco: 245000.0,
        },
        {
          id: 85,
          tipo: "Terreno",
          endereco: "Rua Y, 123",
          preco: 185000.0,
        },
        {
          id: 86,
          tipo: "Casa",
          endereco: "Rua dos Jasmins, 890",
          preco: 435000.0,
        },
        {
          id: 87,
          tipo: "Apartamento",
          endereco: "Rua Suriname, 123",
          preco: 365000.0,
        },
        {
          id: 88,
          tipo: "Terreno",
          endereco: "Rua Z, 234",
          preco: 105000.0,
        },
        {
          id: 89,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 901",
          preco: 405000.0,
        },
        {
          id: 90,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 234",
          preco: 255000.0,
        },
        {
          id: 91,
          tipo: "Terreno",
          endereco: "Rua 1, 345",
          preco: 195000.0,
        },
        {
          id: 92,
          tipo: "Casa",
          endereco: "Rua das Azaleias, 012",
          preco: 445000.0,
        },
        {
          id: 93,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 345",
          preco: 375000.0,
        },
        {
          id: 94,
          tipo: "Terreno",
          endereco: "Rua 2, 456",
          preco: 125000.0,
        },
        {
          id: 95,
          tipo: "Casa",
          endereco: "Rua das Gardênias, 123",
          preco: 415000.0,
        },
        {
          id: 96,
          tipo: "Apartamento",
          endereco: "Rua Chile, 456",
          preco: 265000.0,
        },
        {
          id: 97,
          tipo: "Terreno",
          endereco: "Rua 3, 567",
          preco: 175000.0,
        },
        {
          id: 98,
          tipo: "Casa",
          endereco: "Rua das Camélias, 234",
          preco: 455000.0,
        },
        {
          id: 99,
          tipo: "Apartamento",
          endereco: "Rua Uruguai, 567",
          preco: 385000.0,
        },
        {
          id: 100,
          tipo: "Terreno",
          endereco: "Rua 4, 678",
          preco: 135000.0,
        },
        {
          id: 101,
          tipo: "Casa",
          endereco: "Rua das Begônias, 345",
          preco: 425000.0,
        },
        {
          id: 102,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 678",
          preco: 275000.0,
        },
        {
          id: 103,
          tipo: "Terreno",
          endereco: "Rua 5, 789",
          preco: 185000.0,
        },
        {
          id: 104,
          tipo: "Casa",
          endereco: "Rua das Dálias, 456",
          preco: 465000.0,
        },
        {
          id: 105,
          tipo: "Apartamento",
          endereco: "Rua Bolívia, 789",
          preco: 395000.0,
        },
        {
          id: 106,
          tipo: "Terreno",
          endereco: "Rua 6, 890",
          preco: 145000.0,
        },
        {
          id: 107,
          tipo: "Casa",
          endereco: "Rua das Tulipas, 567",
          preco: 435000.0,
        },
        {
          id: 108,
          tipo: "Apartamento",
          endereco: "Rua Peru, 890",
          preco: 285000.0,
        },
        {
          id: 109,
          tipo: "Terreno",
          endereco: "Rua 7, 901",
          preco: 195000.0,
        },
        {
          id: 110,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          preco: 358800.0,
        },
      ],
      imoveisRecentes: [
        {
          id: 3,
          tipo: "Terreno",
          endereco: "Rua Verde, 789",
          dataCadastro: "2025-07-29",
        },
        {
          id: 13,
          tipo: "Terreno",
          endereco: "Rua das Flores, 789",
          dataCadastro: "2025-06-14",
        },
        {
          id: 15,
          tipo: "Apartamento",
          endereco: "Rua Portugal, 567",
          dataCadastro: "2025-08-16",
        },
        {
          id: 26,
          tipo: "Casa",
          endereco: "Rua das Acácias, 678",
          dataCadastro: "2025-07-13",
        },
        {
          id: 29,
          tipo: "Casa",
          endereco: "Rua dos Lírios, 789",
          dataCadastro: "2025-08-14",
        },
        {
          id: 30,
          tipo: "Apartamento",
          endereco: "Rua Paraguai, 012",
          dataCadastro: "2025-07-10",
        },
        {
          id: 38,
          tipo: "Casa",
          endereco: "Rua das Margaridas, 012",
          dataCadastro: "2025-06-29",
        },
        {
          id: 40,
          tipo: "Terreno",
          endereco: "Rua J, 678",
          dataCadastro: "2025-07-21",
        },
        {
          id: 45,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          dataCadastro: "2025-06-23",
        },
        {
          id: 49,
          tipo: "Terreno",
          endereco: "Rua M, 890",
          dataCadastro: "2025-06-14",
        },
        {
          id: 50,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 345",
          dataCadastro: "2025-08-23",
        },
        {
          id: 53,
          tipo: "Casa",
          endereco: "Rua das Begônias, 456",
          dataCadastro: "2025-07-27",
        },
        {
          id: 54,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 789",
          dataCadastro: "2025-08-18",
        },
        {
          id: 59,
          tipo: "Casa",
          endereco: "Rua das Tulipas, 678",
          dataCadastro: "2025-08-19",
        },
        {
          id: 64,
          tipo: "Terreno",
          endereco: "Rua R, 345",
          dataCadastro: "2025-06-07",
        },
        {
          id: 70,
          tipo: "Terreno",
          endereco: "Rua T, 567",
          dataCadastro: "2025-08-20",
        },
        {
          id: 71,
          tipo: "Casa",
          endereco: "Rua dos Girassóis, 012",
          dataCadastro: "2025-07-14",
        },
        {
          id: 76,
          tipo: "Terreno",
          endereco: "Rua V, 890",
          dataCadastro: "2025-06-23",
        },
        {
          id: 81,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 901",
          dataCadastro: "2025-05-29",
        },
        {
          id: 89,
          tipo: "Casa",
          endereco: "Rua das Hortênsias, 901",
          dataCadastro: "2025-08-16",
        },
        {
          id: 90,
          tipo: "Apartamento",
          endereco: "Rua Guiana Francesa, 234",
          dataCadastro: "2025-07-21",
        },
        {
          id: 93,
          tipo: "Apartamento",
          endereco: "Rua Argentina, 345",
          dataCadastro: "2025-09-01",
        },
        {
          id: 104,
          tipo: "Casa",
          endereco: "Rua das Dálias, 456",
          dataCadastro: "2025-06-12",
        },
        {
          id: 108,
          tipo: "Apartamento",
          endereco: "Rua Peru, 890",
          dataCadastro: "2025-08-09",
        },
        {
          id: 110,
          tipo: "Apartamento",
          endereco: "Rua Venezuela, 456",
          dataCadastro: "2025-08-13",
        },
      ],
      caracteristicasImovelMaisVisitado: {
        id: 2,
        tipo: "Apartamento",
        endereco: "Av. Brasil, 456",
        preco: 1200000.0,
        descricao: "Apartamento de luxo",
        acessos: 9,
      },
    },
    usuarios: {
      totalAdministradores: 4,
      totalVisitantes: 4,
      totalUsuarios: 20,
    },
    vendas: {
      totalVenda: 54,
      vendasPorTipo: [
        {
          tipoImovel: "Apartamento",
          quantidade: 0,
          porcentagem: 0.0,
        },
        {
          tipoImovel: "Casa",
          quantidade: 0,
          porcentagem: 0.0,
        },
        {
          tipoImovel: "Terreno",
          quantidade: 0,
          porcentagem: 0.0,
        },
      ],
      vendasPorTipoMes: [
        {
          mes: "2025-09",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-09",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-09",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2025-08",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-08",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-08",
          tipo: "Terreno",
          total: 1,
        },
        {
          mes: "2025-07",
          tipo: "Apartamento",
          total: 1,
        },
        {
          mes: "2025-07",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-07",
          tipo: "Terreno",
          total: 1,
        },
        {
          mes: "2025-06",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-06",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-06",
          tipo: "Terreno",
          total: 2,
        },
        {
          mes: "2025-05",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-05",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-05",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2025-04",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-04",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-04",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2025-03",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-03",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-03",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2025-02",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-02",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-02",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2025-01",
          tipo: "Apartamento",
          total: 1,
        },
        {
          mes: "2025-01",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2025-01",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2024-12",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2024-12",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2024-12",
          tipo: "Terreno",
          total: 2,
        },
        {
          mes: "2024-11",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2024-11",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2024-11",
          tipo: "Terreno",
          total: 0,
        },
        {
          mes: "2024-10",
          tipo: "Apartamento",
          total: 0,
        },
        {
          mes: "2024-10",
          tipo: "Casa",
          total: 0,
        },
        {
          mes: "2024-10",
          tipo: "Terreno",
          total: 2,
        },
      ],
      vendasPorPreco: [
        {
          id: 12,
          tipo: "Apartamento",
          preco: 280000.0,
          dataVenda: "2025-01-05",
        },
        {
          id: 16,
          tipo: "Terreno",
          preco: 95000.0,
          dataVenda: "2024-07-01",
        },
        {
          id: 21,
          tipo: "Apartamento",
          preco: 265000.0,
          dataVenda: "2024-06-28",
        },
        {
          id: 25,
          tipo: "Terreno",
          preco: 120000.0,
          dataVenda: "2024-10-30",
        },
        {
          id: 30,
          tipo: "Apartamento",
          preco: 245000.0,
          dataVenda: "2025-07-10",
        },
        {
          id: 34,
          tipo: "Terreno",
          preco: 140000.0,
          dataVenda: "2024-01-19",
        },
        {
          id: 40,
          tipo: "Terreno",
          preco: 125000.0,
          dataVenda: "2025-07-21",
        },
        {
          id: 46,
          tipo: "Terreno",
          preco: 135000.0,
          dataVenda: "2024-05-27",
        },
        {
          id: 52,
          tipo: "Terreno",
          preco: 115000.0,
          dataVenda: "2024-12-14",
        },
        {
          id: 58,
          tipo: "Terreno",
          preco: 105000.0,
          dataVenda: "2024-06-07",
        },
        {
          id: 64,
          tipo: "Terreno",
          preco: 95000.0,
          dataVenda: "2025-06-07",
        },
        {
          id: 70,
          tipo: "Terreno",
          preco: 125000.0,
          dataVenda: "2025-08-20",
        },
        {
          id: 76,
          tipo: "Terreno",
          preco: 135000.0,
          dataVenda: "2025-06-23",
        },
        {
          id: 82,
          tipo: "Terreno",
          preco: 115000.0,
          dataVenda: "2024-04-18",
        },
        {
          id: 88,
          tipo: "Terreno",
          preco: 105000.0,
          dataVenda: "2024-07-05",
        },
        {
          id: 94,
          tipo: "Terreno",
          preco: 125000.0,
          dataVenda: "2024-10-16",
        },
        {
          id: 100,
          tipo: "Terreno",
          preco: 135000.0,
          dataVenda: "2024-12-23",
        },
        {
          id: 106,
          tipo: "Terreno",
          preco: 145000.0,
          dataVenda: "2024-08-04",
        },
      ],
    },
    alugueis: {
      totalLocacao: 19,
      alugueisPorMes: [
        {
          mes: "2025-09",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-09",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2025-09",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-08",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-08",
          tipoImovel: "Casa",
          total: 1,
        },
        {
          mes: "2025-08",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-07",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-07",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2025-07",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-06",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-06",
          tipoImovel: "Casa",
          total: 2,
        },
        {
          mes: "2025-06",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-05",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-05",
          tipoImovel: "Casa",
          total: 1,
        },
        {
          mes: "2025-05",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-04",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-04",
          tipoImovel: "Casa",
          total: 1,
        },
        {
          mes: "2025-04",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-03",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-03",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2025-03",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-02",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-02",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2025-02",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2025-01",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2025-01",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2025-01",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2024-12",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2024-12",
          tipoImovel: "Casa",
          total: 0,
        },
        {
          mes: "2024-12",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2024-11",
          tipoImovel: "Apartamento",
          total: 0,
        },
        {
          mes: "2024-11",
          tipoImovel: "Casa",
          total: 3,
        },
        {
          mes: "2024-11",
          tipoImovel: "Terreno",
          total: 0,
        },
        {
          mes: "2024-10",
          tipoImovel: "Apartamento",
          total: 1,
        },
        {
          mes: "2024-10",
          tipoImovel: "Casa",
          total: 1,
        },
        {
          mes: "2024-10",
          tipoImovel: "Terreno",
          total: 0,
        },
      ],
    },
  };
}
