export const mockImoveis = [
  {
    id: 1,
    tipo: "Casa",
    endereco: "Rua das Flores, 123",
    cidade: "São Paulo",
    estado: "SP",
    preco: 1320000,
    status: "Disponível",
    area: 346,
    descricao: "Casa ampla com quintal e garagem.",
    data_cadastro: "2025-08-01",
    quartos: 5,
    banheiros: 4,
    vagas: 3,
    possui_piscina: false,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/casa.png",
        descricao: "Fachada da casa",
      },
    ],
    bairro: "Vila Ponce",
  },
  {
    id: 2,
    tipo: "Apartamento",
    endereco: "Av. Central, 45",
    cidade: "São Paulo",
    estado: "SP",
    preco: 960000,
    status: "Disponível",
    area: 202,
    descricao: "Apartamento moderno com ótima localização.",
    data_cadastro: "2025-08-01",
    quartos: 4,
    banheiros: 3,
    vagas: 2,
    possui_piscina: false,
    possui_jardim: false,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Sala de estar",
      },
    ],
    bairro: "Centro",
  },
  {
    id: 3,
    tipo: "Apartamento",
    endereco: "Rua São Francisco, 89",
    cidade: "São Paulo",
    estado: "SP",
    preco: 631000,
    status: "Disponível",
    area: 189,
    descricao: "Apartamento funcional, ideal para famílias.",
    data_cadastro: "2025-08-01",
    quartos: 3,
    banheiros: 2,
    vagas: 1,
    possui_piscina: false,
    possui_jardim: false,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Cozinha planejada",
      },
      {
        url_imagem: "/images/slide1.png",
        descricao: "Quarto principal",
      },
    ],
    bairro: "Vila São Francisco",
  },
  {
    id: 4,
    tipo: "Apartamento",
    endereco: "Rua Fátima, 201",
    cidade: "São Paulo",
    estado: "SP",
    preco: 460000,
    status: "Disponível",
    area: 193,
    descricao: "Apartamento compacto e aconchegante.",
    data_cadastro: "2025-08-01",
    quartos: 3,
    banheiros: 2,
    vagas: 1,
    possui_piscina: false,
    possui_jardim: false,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Quarto principal",
      },
    ],
    bairro: "Vila Fátima",
  },
  {
    id: 5,
    tipo: "Casa",
    endereco: "Rua Nosso Teto, 98",
    cidade: "São Paulo",
    estado: "SP",
    preco: 790000,
    status: "Disponível",
    area: 314,
    descricao: "Casa com edícula e garagem para 2 carros.",
    data_cadastro: "2025-08-01",
    quartos: 4,
    banheiros: 3,
    vagas: 2,
    possui_piscina: false,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Fachada da casa",
      },
    ],
    bairro: "Nosso Teto",
  },
  {
    id: 6,
    tipo: "Casa",
    endereco: "Rua das Palmeiras, 77",
    cidade: "São Paulo",
    estado: "SP",
    preco: 325000,
    status: "Disponível",
    area: 185,
    descricao: "Casa simples e bem localizada.",
    data_cadastro: "2025-08-01",
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    possui_piscina: false,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Frente da casa",
      },
    ],
    bairro: "Jardim das Palmeiras",
  },
  {
    id: 7,
    tipo: "Casa",
    endereco: "Rua Hatari, 31",
    cidade: "São Paulo",
    estado: "SP",
    preco: 890000,
    status: "Disponível",
    area: 365,
    descricao: "Casa espaçosa com jardim.",
    data_cadastro: "2025-08-01",
    quartos: 5,
    banheiros: 3,
    vagas: 3,
    possui_piscina: true,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Área externa",
      },
    ],
    bairro: "Jardim Hatari",
  },
  {
    id: 8,
    tipo: "Casa",
    endereco: "Rua Ribeirópolis, 21",
    cidade: "São Paulo",
    estado: "SP",
    preco: 750000,
    status: "Disponível",
    area: 314,
    descricao: "Casa com quintal grande.",
    data_cadastro: "2025-08-01",
    quartos: 4,
    banheiros: 2,
    vagas: 2,
    possui_piscina: false,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Entrada da casa",
      },
    ],
    bairro: "Vila Ribeirópolis",
  },
  {
    id: 9,
    tipo: "Casa",
    endereco: "Rua Tupy, 15",
    cidade: "São Paulo",
    estado: "SP",
    preco: 515000,
    status: "Disponível",
    area: 202,
    descricao: "Casa charmosa em bairro tranquilo.",
    data_cadastro: "2025-08-01",
    quartos: 3,
    banheiros: 2,
    vagas: 1,
    possui_piscina: false,
    possui_jardim: true,
    imagens: [
      {
        url_imagem: "/images/slide1.png",
        descricao: "Sala de estar",
      },
    ],
    bairro: "Vila Tupy",
  },
];
